spring:
  application:
    name: polygonMap

  data:
    mongodb:
      user: user
      password: password
      uri: mongodb://127.0.0.1:27017/testPolygonMap
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 100
