spring:
  application:
    name: polygonMap
  data:
    mongodb:
      user: user
      password: password
      uri: mongodb://127.0.0.1:27017/test?timeoutMS=1000&connectTimeoutMS=1000&serverSelectionTimeoutMS=1000
      autoCommit: true
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 100
#logging:
#  level:
#    root: DEBUG
#    org:
#      hibernate: DEBUG
#      polygonMap:
#        backend: DEBUG
#      springframework:
#        web: DEBUG
